'use strict'

module.exports = {
    boundary: '--++__astilectron_boundary__++--',
    eventNames: {
        appEventReady: "app.event.ready",
        windowCmdBlur: "window.cmd.blur",
        windowCmdCenter: "window.cmd.center",
        windowCmdClose: "window.cmd.close",
        windowCmdCreate: "window.cmd.create",
        windowCmdDestroy: "window.cmd.destroy",
        windowCmdFocus: "window.cmd.focus",
        windowCmdHide: "window.cmd.hide",
        windowCmdMaximize: "window.cmd.maximize",
        windowCmdMinimize: "window.cmd.minimize",
        windowCmdMove: "window.cmd.move",
        windowCmdResize: "window.cmd.resize",
        windowCmdRestore: "window.cmd.restore",
        windowCmdShow: "window.cmd.show",
        windowCmdUnmaximize: "window.cmd.unmaximize",
        windowDoneCreate: "window.done.create",
        windowEventBlur: "window.event.blur",
        windowEventClosed: "window.event.closed",
        windowEventFocus: "window.event.focus",
        windowEventHide: "window.event.hide",
        windowEventMaximize: "window.event.maximize",
        windowEventMinimize: "window.event.minimize",
        windowEventMove: "window.event.move",
        windowEventReadyToShow: "window.event.ready.to.show",
        windowEventResize: "window.event.resize",
        windowEventRestore: "window.event.restore",
        windowEventShow: "window.event.show",
        windowEventUnmaximize: "window.event.unmaximize",
        windowEventUnresponsive: "window.event.unresponsive",
    },
    mainTargetID: 'main'
}
